### ISSUE TITLE
Upgrade for python 35u

### ISSUE THREAD

**Issue by appcove** [iuscommunity-pkg/python35u-postgresql#1]
Hello,

There has been an important bug fix upstream with regards to PostgreSQL9.5 jsonb support.  Please re-build the package against the master branch:

https://github.com/python-postgres/fe/tree/master

Thanks!

**Comment by carlwgeorge** [comment]
Howdy @appcove,

IUS stands for **I**nline with **U**pstream **S**table.  This means we build upstream stable releases, not git snapshots.  Unfortunately I see that the [commit](https://github.com/python-postgres/fe/commit/2f2df7a3abf06f032b05122677a1937032b51a9c) you mentioned previously has not yet made it into a stable release.  It might be possible to cherry pick just that commit as a patch onto the last 1.1.0 release, but we don't yet know if that will work or will even be sufficient to fix the problem you are trying to address.  I'm happy to engage upstream about this, but before I open an issue, do you know of any existing relevant discussion on issues, mailing lists, or forums?

**Comment by appcove** [comment]
I noticed the last release was 2012 - so I need to ask the developers what
is going on.

I'll post back here.

## 

Jason Garber, President
AppCove, Inc.
(814) 240-3338

**Comment by b-harper** [comment]
Hey @appcove,

The py-postgresql module got an update to 1.2.1.  This update only shows up on the [pypi page][0], but not the [home page][1] or the [GitHub repository][2].  This new release does contain the changes from the [commit][3] @carlwgeorge was able to track down.  

Updated packages are in the testing repositories. Please let us know if this update addresses your concerns. 

[0]: https://pypi.python.org/pypi/py-postgresql
[1]: http://python.projects.pgfoundry.org
[2]: https://github.com/python-postgres/fe/releases
[3]: https://github.com/python-postgres/fe/commit/2f2df7a3abf06f032b05122677a1937032b51a9c

**Comment by b-harper** [comment]
The 1.2.1 packages have been in the testing repositories for two weeks and will be moved to the stable repositories during tonight's automation.  @appcove, please let us know if you have any concerns.
